version: "2"
services:
    www:
        build: .
        ports: 
            - "80:80"
            - "443:443"
        volumes:
            - ${WORKING_DIR_PHP}/ccdamkar:/var/www/html/
            - ./mycert.crt:/etc/ssl/certs/mycert.crt
            - ./mycert.key:/etc/ssl/private/mycert.key
        links:
            - db
        networks:
            - default
        environment:
            CI_ENV: local
    db:
        image: mysql:5.6
        ports: 
            - "3306:3306"
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
volumes:
    persistent: